spring:
  thymeleaf:
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
    #encoding: UTF-8
    #content-type: text/html
    mode: LEGACYHTML5
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  freemarker:
    suffix: .ftl
  resources:
    add-mappings: true
comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png

